### ISSUE TITLE
Feature: add review for deep dive

### ISSUE THREAD

**Issue by exp0nge** [NazimAmin/RateCUNY#1]
It would be helpful if the ticker had a deeper view for when you click on one course, currently it does nothing.

**Comment by nazimamin** [comment]
@exp0nge when you click on the rating and if that profile is also available in ratemyprofessor, it should open a new window linking to that profile in rmp's website.

**Comment by exp0nge** [comment]
Not that one, but when you click a course and CUNYfirst takes you into a deeper view of the requirements and course description, the ticker should be there also. This would also give you more options to expand the extension to do more so I won't need to go to RMP if I can just see a few comments on that deep dive view.
